# Introduction to Retrieval Augmented Generation with S&P 500 news

In this notebook, you will explore how to build a simple Retrieval-Augmented Generation (RAG) pipeline using financial news articles from S&P 500 companies.

We'll start by vectorizing text data, creating a vector store using FAISS, and integrating it with OpenAI's GPT models to answer questions using retrieved information.

This workflow emulates real-world systems in finance where natural language data (news, filings, analyst reports) are used to support decision-making.

# 📌 Objectives

By the end of this notebook, students will be able to:

1. **Perform Semantic Search with Metadata Filtering:**
   - Query the provided FAISS vector store to retrieve relevant financial news articles based on natural language questions.
   - Apply optional filters using metadata such as ticker or publication date to refine search results.

2. **Enrich Data with Company Metadata:**
   - Use the `yfinance` library to retrieve company-level metadata (company name, sector, industry) for tickers in the dataset.
   - Integrate this metadata to support enhanced filtering and analysis of news data.

3. **Build a Retrieval-Augmented Generation (RAG) Pipeline:**
   - Combine retrieved news snippets as context to generate answers using OpenAI’s GPT models.
   - Construct effective prompts that guide the language model to provide concise, context-aware responses.

4. **Evaluate and Analyze RAG Outputs:**
   - Review generated answers alongside the supporting news excerpts.
   - Reflect on the strengths and limitations of the simple RAG pipeline and consider potential improvements, such as adding more filters or refining retrieval strategies.

5. **Incorporate Financial Metadata into Retrieval Context:**
   - Enrich retrieved news snippets with key financial metadata including ticker, company name, sector, and industry.
   - Format prompts that combine both text excerpts and metadata to provide richer context to the language model.

6. **Generate Context-Aware Answers Using OpenAI Models:**
   - Construct and send prompts to an LLM that leverage both news content and metadata to produce concise, informed financial analysis.

7. **Compare Answers With and Without Metadata:**
   - Evaluate the impact of including financial metadata on answer quality using criteria such as clarity, detail, accuracy, and contextual relevance.
   - Summarize findings to reflect on the role of metadata in improving retrieval-augmented generation.

## Install and Import important librairies

First, we install and import the necessary libraries for:
- Text embedding generation (sentence-transformers)
- Efficient similarity search (faiss)
- Data manipulation (pandas, numpy)
- Visualization (matplotlib)

> ℹ️ FAISS uses inner product for cosine similarity by normalizing vectors.

In [ ]:
%pip install sentence-transformers
%pip install faiss-cpu

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (5.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.55.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.34.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.7)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.11/dist-packages (1.12.0)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from faiss-cpu) (25.0)

In [ ]:
from sentence_transformers import SentenceTransformer
import faiss
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from collections import Counter
import matplotlib.pyplot as plt
import faiss
from sentence_transformers import util

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
DIR = "/content/drive/MyDrive/FINTECH"
os.chdir(DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Load news data
We load a CSV file of financial news, focusing on TITLE and SUMMARY, along with metadata like TICKER and PUBLICATION_DATE.
These will be embedded into vectors and used for semantic retrieval.

In [ ]:
K = 25

In [ ]:
df_news = pd.read_csv('df_news.csv')
df_news['PUBLICATION_DATE'] = pd.to_datetime(df_news['PUBLICATION_DATE']).dt.date
display(df_news)

,TICKER,TITLE,SUMMARY,PUBLICATION_DATE,PROVIDER,URL
0,MMM,2 Dow Jones Stocks with Promising Prospects an...,The Dow Jones (^DJI) is made up of 30 of the m...,2025-05-29,StockStory,https://finance.yahoo.com/news/2-dow-jones-sto...
1,MMM,3 S&P 500 Stocks Skating on Thin Ice,The S&P 500 (^GSPC) is often seen as a benchma...,2025-05-27,StockStory,https://finance.yahoo.com/news/3-p-500-stocks-...
2,MMM,3M Rises 15.8% YTD: Should You Buy the Stock N...,"MMM is making strides in the aerospace, indust...",2025-05-22,Zacks,https://finance.yahoo.com/news/3m-rises-15-8-y...
3,MMM,Q1 Earnings Roundup: 3M (NYSE:MMM) And The Res...,Quarterly earnings results are a good time to ...,2025-05-22,StockStory,https://finance.yahoo.com/news/q1-earnings-rou...
4,MMM,3 Cash-Producing Stocks with Questionable Fund...,While strong cash flow is a key indicator of s...,2025-05-19,StockStory,https://finance.yahoo.com/news/3-cash-producin...
...,...,...,...,...,...,...
4866,ZTS,2 Dividend Stocks to Buy With $500 and Hold Fo...,Zoetis is a leading animal health company with...,2025-05-23,Motley Fool,https://www.fool.com/investing/2025/05/23/2-di...
4867,ZTS,Zoetis (NYSE:ZTS) Declares US$0.50 Dividend Pe...,Zoetis (NYSE:ZTS) recently affirmed a dividend...,2025-05-22,Simply Wall St.,https://finance.yahoo.com/news/zoetis-nyse-zts...
4868,ZTS,Jim Cramer on Zoetis (ZTS): “It Does Seem to B...,We recently published a list of Jim Cramer Tal...,2025-05-21,Insider Monkey,https://finance.yahoo.com/news/jim-cramer-zoet...
4869,ZTS,Zoetis (ZTS) Upgraded to Buy: Here's Why,Zoetis (ZTS) might move higher on growing opti...,2025-05-21,Zacks,https://finance.yahoo.com/news/zoetis-zts-upgr...
4870,ZTS,ZTS Q1 Earnings Call: Guidance Raised as Platf...,Animal health company Zoetis (NYSE:ZTS) report...,2025-05-19,StockStory,https://finance.yahoo.com/news/zts-q1-earnings...

In [ ]:
df_news['EMBEDDED_TEXT'] = df_news['TITLE'] + ' : ' + df_news['SUMMARY']

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

## Implement FAISS vector store
We:
- Use a pre-trained sentence transformer (all-MiniLM-L6-v2) to embed documents.
- Normalize vectors to use cosine similarity.
- Create a FAISS index and implement a basic search function.

This will allow us to retrieve relevant news snippets given a natural language question.

In [ ]:
# Load model and compute embeddings
text_embeddings = model.encode(df_news['EMBEDDED_TEXT'].tolist(), convert_to_numpy=True)

# Normalize embeddings to use cosine similarity (via inner product in FAISS)
text_embeddings = text_embeddings / np.linalg.norm(text_embeddings, axis=1, keepdims=True)

# Prepare metadata
documents = df_news['EMBEDDED_TEXT'].tolist()
metadata = [
    {
        'PUBLICATION_DATE': row['PUBLICATION_DATE'],
        'TICKER': row['TICKER'],
        'PROVIDER': row['PROVIDER']
    }
    for _, row in df_news.iterrows()
]

In [ ]:
embedding_dim = text_embeddings.shape[1]
faiss_index = faiss.IndexFlatIP(embedding_dim)  # Cosine similarity via inner product
faiss_index.add(text_embeddings)

In [ ]:
class FaissVectorStore:
    def __init__(self, model, index, embeddings, documents, metadata):
        self.model = model
        self.index = index
        self.embeddings = embeddings
        self.documents = documents
        self.metadata = metadata

    def search(self, query, k=25, metadata_filter=None):
        query_embedding = self.model.encode([query])
        query_embedding = query_embedding / np.linalg.norm(query_embedding)

        if metadata_filter:
            filtered_indices = [i for i, meta in enumerate(self.metadata) if metadata_filter(meta)]
            if not filtered_indices:
                return []
            filtered_embeddings = self.embeddings[filtered_indices]
            temp_index = faiss.IndexFlatIP(filtered_embeddings.shape[1])
            temp_index.add(filtered_embeddings)
            D, I = temp_index.search(query_embedding, k)
            indices = [filtered_indices[i] for i in I[0]]
        else:
            D, I = self.index.search(query_embedding, k)
            indices = I[0]
            D = D[0]

        results = []
        for idx, sim in zip(indices, D):
            results.append((self.documents[idx], self.metadata[idx], float(sim)))
        return results

In [ ]:
# Create FAISS-based store
faiss_store = FaissVectorStore(
    model=model,
    index=faiss_index,
    embeddings=text_embeddings,
    documents=documents,
    metadata=metadata
)

### Setup OpenAI Client

👉 **Instructions**:
- Import the `OpenAI` client from the `openai` Python library.
- You will need an **OpenAI API key** to use their models programmatically:
  - Go to [https://platform.openai.com/](https://platform.openai.com/) and sign up or log in.
  - Create an API key from your [API keys dashboard](https://platform.openai.com/account/api-keys).
  - ⚠️ **Keep your API key private** and **do not** share or hardcode it in public notebooks.
- Note that **usage of the OpenAI API is not free**. You will need to:
  - Add a payment method.
  - Monitor your usage to avoid unexpected charges.
  - Optionally set usage limits from your account settings.
- You can refer to the **course’s Study Resources** for a step-by-step guide on creating an OpenAI account and retrieving your API key.

Then:
- Initialize the client with `OpenAI(api_key="YOUR_KEY_HERE")`.
- Send a test request using `.responses.create()` and the `"gpt-4o-mini"` model with a simple prompt:

  ```python
  response = client.responses.create(
      model="gpt-4o-mini",
      input="Write a one-sentence bedtime story about a unicorn."
  )
  print(response.output_text)

In [ ]:
# Read the OpenAI API key from a private file
# You stored your API key in a .txt file inside your Google Drive
# to avoid exposing it directly in the code

with open('/content/drive/MyDrive/FINTECH/api_key.txt') as f:
    api_key = f.read().strip()

from openai import OpenAI
client = OpenAI(api_key=api_key)

In [ ]:
response = client.responses.create(
    model="gpt-4o-mini",
    input="Write a one-sentence bedtime story about a unicorn."
)
print(response.output_text)

As the stars twinkled like diamonds in the night sky, Luna the unicorn spread her iridescent wings and soared through dreamland, sprinkling stardust on every child to fill their hearts with joy and wonder.

## Retrieve Additional Metadata from Yahoo Finance

👉 **Instructions**:
- We will enrich our news dataset by retrieving **company-level metadata** using the `yfinance` library.
- The goal is to map each unique stock ticker (`TICKER`) in the dataset to:
  - `COMPANY_NAME`
  - `SECTOR`
  - `INDUSTRY`

> ℹ️ `yfinance` fetches live data from Yahoo Finance. If you're running this in a cloud environment or during peak hours, expect some tickers to fail or rate limits to apply.

✅ After this step, you will have a new DataFrame (e.g. `df_meta`) with the columns `TICKER`, `COMPANY_NAME`, `SECTOR`, `INDUSTRY` that maps tickers to their company names, sectors, and industries. This metadata will be useful later to add filters and analysis based on sector or industry categories.

In [ ]:
import yfinance as yf

unique_tickers = df_news['TICKER'].unique()

#prepare a list to store metadata
metadata = []

for ticker in unique_tickers:
  try:
    stock = yf.Ticker(ticker)
    info = stock.info #fetch company information

    metadata.append({
        'TICKER': ticker,
        'COMPANY_NAME': info.get('longName'),
        'SECTOR': info.get('sector'),
        'INDUSTRY': info.get('industry')
    })

  except Exception as e:
    print(f"Error fetching data for {ticker}: {e}")
    metadata.append({
        'TICKER': ticker,
        'COMPANY_NAME': None,
        'SECTOR': None,
        'INDUSTRY': None
    })

#create dataframe with metadata
df_meta = pd.DataFrame(metadata)

#display sample
df_meta.head()

,TICKER,COMPANY_NAME,SECTOR,INDUSTRY
0,MMM,3M Company,Industrials,Conglomerates
1,AOS,A. O. Smith Corporation,Industrials,Specialty Industrial Machinery
2,ABT,Abbott Laboratories,Healthcare,Medical Devices
3,ABBV,AbbVie Inc.,Healthcare,Drug Manufacturers - General
4,ACN,Accenture plc,Technology,Information Technology Services

## Retrieval-Augmented Generation (RAG): Retrieve Documents and Generate Answers

👉 **Instructions**:

In this part of the assignment, your task is to build a simple Retrieval-Augmented Generation (RAG) pipeline that:

- Takes a user question as input.
- Searches the FAISS vector store to find a set of relevant financial news articles based on semantic similarity.
- Uses the retrieved news articles as context to generate a clear, concise answer to the question by interacting with the OpenAI language model.
- Returns both the generated answer and the underlying news snippets used for context.

### What you need to focus on:

- Implement a retrieval mechanism to query your vector store and obtain the top relevant documents for any question.
- Construct prompts that effectively combine retrieved news content with the user’s question to guide the language model’s response.
- Use the OpenAI API to generate answers grounded in the retrieved context.
- Organize the outputs so that for each question, you have:
  - The generated answer.
  - The collection of news excerpts used to produce that answer.

### What you will be provided:

- Helper functions to display outputs in markdown format.
- Lists of example questions covering topics, companies, and industries to test your implementation.

---

Your solution can take any form or structure you find appropriate, as long as it fulfills these core objectives. This exercise will give you hands-on experience with integrating retrieval and generation for practical applications in finance.

#### Print markdown
You can use the following function to print answers from GPT4o-mini in markdown.

In [ ]:
from IPython.display import Markdown, display

def print_markdown(text):
    display(Markdown(text))

#### Predefined questions

In [ ]:
questions_topic = [
"What are the major concerns expressed in financial news about inflation?",
"How is investor sentiment described in recent financial headlines?",
"What role is artificial intelligence playing in recent finance-related news stories?"
]

questions_company = [
"How is Microsoft being portrayed in news stories about artificial intelligence?",
"What financial news headlines connect Amazon with automation or logistics?"
]

questions_industry = [
"What are the main themes emerging in financial news about the semiconductor industry?",
"What trends are being reported in the retail industry?",
"What risks or challenges are discussed in recent news about the energy industry?"
]

In [ ]:
import textwrap

def retrieve_and_generate_with_scores(question, faiss_index, df_news, model, client, k=25):
    """
    Retrieve top-k relevant news snippets from FAISS and use them as context
    to generate a concise answer using OpenAI GPT, printing retrieval scores.
    """
    # Search for relevant documents using FAISS
    query_embedding = model.encode([question], convert_to_numpy=True)
    query_embedding = query_embedding / (np.linalg.norm(query_embedding, axis=1, keepdims=True) + 1e-10)  # Normalize

    scores, indices = faiss_index.search(query_embedding, k)

    retrieved_snippets = []
    for idx, score in zip(indices[0], scores[0]):
        meta = df_news.iloc[idx]
        snippet = meta['SUMMARY']
        retrieved_snippets.append((snippet, meta.to_dict(), score))

    # Build context
    context_text = "\n\n".join(
        f"[{meta['TICKER']} | {meta['PUBLICATION_DATE']}]: {snippet}"
        for snippet, meta, _ in retrieved_snippets
    )

    # Construct prompt
    prompt = f"""
You are a financial news assistant.
Answer the following question based only on the context provided.

Question:
{question}

Context:
{context_text}

Answer:
"""
    # Generate answer
    response = client.responses.create(
        model="gpt-4o-mini",
        input=prompt
    )

    return response.output_text, retrieved_snippets


# Loop through all questions and print results
def run_all_questions():
    all_sets = {
        "Topic Questions": questions_topic,
        "Company Questions": questions_company,
        "Industry Questions": questions_industry
    }

    for set_name, questions in all_sets.items():
        print(f"\n{'='*40}\n{set_name}\n{'='*40}")
        for question in questions:
            answer, docs_used = retrieve_and_generate_with_scores(
                question, faiss_index, df_news, model, client, k=25
            )

            print(f"\n**Question:** {question}")
            print(f"**Answer:** {answer}")

            print("\n--- Context Used ---")
            for snippet, meta, score in docs_used:
                print(f"{meta['TICKER']} | {meta['PUBLICATION_DATE']} | Score: {score:.4f}")
                print(textwrap.fill(snippet, width=100))
                print()


# Run everything
run_all_questions()

========================================
Topic Questions
========================================

**Question:** What are the major concerns expressed in financial news about inflation?
**Answer:** The major concerns expressed in financial news about inflation include:

1. **Persistent Inflation**: There is mounting concern regarding the ongoing nature of inflation, indicating it is not transitory and poses risks of sustained economic impact.

2. **Economic Slowdown**: The Federal Reserve is worried that persistent inflation could lead to a broader economic slowdown.

3. **Rising Costs**: Grocers are facing significant increases in weekly bills due to creeping inflation and new tariffs, affecting the prices of staple items.

4. **Fiscal Health Risks**: There are growing concerns about the sustainability of fiscal policies, especially with the U.S. national debt exceeding $36 trillion, intensifying fears about potential currency devaluation.

5. **Market Reactions**: Analysts are lowering earnings forecasts due to uncertainty in the macroeconomic environment, suggesting that inflation is a significant factor impacting general economic health and investor sentiment.

--- Context Used ---
BLK | 2025-05-29 | Score: 0.5771
The Federal Reserve’s May policy meeting revealed mounting concern over persistent US inflation and
the potential for economic slowdown.

TSLA | 2025-05-31 | Score: 0.4920
Key moments from the last seven days, plus a glimpse at the week ahead

NVDA | 2025-05-31 | Score: 0.4920
Key moments from the last seven days, plus a glimpse at the week ahead

LULU | 2025-05-31 | Score: 0.4920
Key moments from the last seven days, plus a glimpse at the week ahead

AVGO | 2025-05-31 | Score: 0.4920
Key moments from the last seven days, plus a glimpse at the week ahead

DLTR | 2025-05-29 | Score: 0.4771
Once again, creeping inflation and new tariffs have caused your weekly grocery bills to seemingly
skyrocket. Popular items like orange juice, eggs, chicken breasts, fresh ground beef, bacon,
seafood,...

BSX | 2025-05-30 | Score: 0.4531
What trends should we look for it we want to identify stocks that can multiply in value over the
long term? One common...

KMX | 2025-05-26 | Score: 0.4528
Wall Street has set ambitious price targets for the stocks in this article. While this suggests
attractive upside potential, it’s important to remain skeptical because analysts face institutional
pressures that can sometimes lead to overly optimistic forecasts.

LUV | 2025-05-28 | Score: 0.4512
Salesforce wades back into dealmaking, Southwest drops free checked bags, Trump Media to buy
Bitcoin, and more news to start your day.

RMD | 2025-05-23 | Score: 0.4483
Exciting developments are taking place for the stocks in this article. They’ve all surged ahead of
the broader market over the last month as catalysts such as new products and positive media coverage
have propelled their returns.

GLW | 2025-05-27 | Score: 0.4370
Wall Street’s bearish price targets for the stocks in this article signal serious concerns. Such
forecasts are uncommon in an industry where maintaining cordial corporate relationships often trumps
delivering the hard truth.

MKC | 2025-05-12 | Score: 0.4318
Wall Street’s bearish price targets for the stocks in this article signal serious concerns. Such
forecasts are uncommon in an industry where maintaining cordial corporate relationships often trumps
delivering the hard truth.

AES | 2025-05-21 | Score: 0.4292
Stocks are lower at midday, putting in jeopardy the six-day winning streak for the S&P 500. Federal
Reserve officials’ commentary is anticipated to provide insights into the central bank’s outlook on
inflation and interest rates, while markets continue digesting the implications of Moody’s recent
downgrade of the U.S. sovereign credit rating, which has heightened concerns about the nation’s
fiscal health as lawmakers debate President Trump’s “big, beautiful” tax bill. Looking ahead,
investors ar

NEM | 2025-05-28 | Score: 0.4283
Amid rising geopolitical tensions, persistent inflation concerns, and growing skepticism about long-
term fiscal discipline, investors increasingly seek stability in hard assets. The U.S. national debt
has surpassed $36 trillion, with annual interest payments approaching $1 trillion. At the same time,
central banks worldwide are significantly increasing their gold reserves, reflecting growing
concerns about fiscal sustainability and potential currency devaluation. In this uncertain
macroeconomic

AOS | 2025-04-30 | Score: 0.4209
Uncertainty about the overall macroeconomic picture continues to be a significant drag on the
earnings outlook as a whole, prompting analysts to cut their estimates for the current and coming
periods.

CBRE | 2025-05-07 | Score: 0.4207
The performance of consumer discretionary businesses is closely linked to economic cycles. This
sensitive demand profile can cause discretionary stocks to plummet when macro uncertainty enters the
fray, and over the past six months, the industry has shed 12.7%. This drawdown was worse than the
S&P 500’s 6.2% loss.

PKG | 2025-04-26 | Score: 0.4204
What trends should we look for it we want to identify stocks that can multiply in value over the
long term? Amongst...

RVTY | 2025-05-23 | Score: 0.4195
Wall Street is overwhelmingly bullish on the stocks in this article, with price targets suggesting
significant upside potential. However, it’s worth remembering that analysts rarely issue sell
ratings, partly because their firms often seek other business from the same companies they cover.

EXPE | 2025-05-17 | Score: 0.4189
(Bloomberg) -- One thing is clear as the first-quarter earnings season draws to a close: The
uncertain outlook for the global economy is superseding better-than-feared results even as stocks
rally on signs of easing trade tensions.Most Read from BloombergAs Coastline Erodes, One California
City Considers ‘Retreat Now’How a Highway Became San Francisco’s Newest ParkMaryland’s Credit Rating
Gets Downgraded as Governor Blames Trump America, ‘Nation of Porches’Power-Hungry Data Centers Are
Warming H

ETR | 2025-05-09 | Score: 0.4136
What trends should we look for it we want to identify stocks that can multiply in value over the
long term? One common...

IT | 2025-05-22 | Score: 0.4135
What trends should we look for it we want to identify stocks that can multiply in value over the
long term? Amongst...

CAT | 2025-05-22 | Score: 0.4110
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

DOV | 2025-05-21 | Score: 0.4103
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

HSIC | 2025-05-21 | Score: 0.4103
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

HAS | 2025-05-14 | Score: 0.4085
The performance of consumer discretionary businesses is closely linked to economic cycles. This
sensitive demand profile can cause discretionary stocks to plummet when macro uncertainty enters the
fray, and over the past six months, the industry has shed 5.8%. This performance was worse than the
S&P 500’s 1% fall.


**Question:** How is investor sentiment described in recent financial headlines?
**Answer:** Investor sentiment in recent financial headlines is largely characterized by an overwhelming bullish outlook, with many articles highlighting significant upside potential for stocks. However, this optimism is tempered by caution, as analysts often issue overly positive forecasts due to institutional pressures and the desire to maintain good relationships with the companies they cover. There are also notable bearish sentiments observed for certain stocks, which stand out given the rarity of negative ratings in the industry, signaling serious concerns amid a primarily positive backdrop.

--- Context Used ---
KMX | 2025-05-26 | Score: 0.6115
Wall Street has set ambitious price targets for the stocks in this article. While this suggests
attractive upside potential, it’s important to remain skeptical because analysts face institutional
pressures that can sometimes lead to overly optimistic forecasts.

MCHP | 2025-05-20 | Score: 0.5978
Great things are happening to the stocks in this article. They’re all outperforming the market over
the last month because of positive catalysts such as a new product line, constructive news flow, or
even a loyal Reddit fanbase.

MPWR | 2025-05-06 | Score: 0.5894
The stocks in this article have caught Wall Street’s attention in a big way, with price targets
implying returns above 20%. But investors should take these forecasts with a grain of salt because
analysts typically say nice things about companies so their firms can win business in other product
lines like M&A advisory.

DRI | 2025-05-21 | Score: 0.5767
When Wall Street turns bearish on a stock, it’s worth paying attention. These calls stand out
because analysts rarely issue grim ratings on companies for fear their firms will lose out in other
business lines such as M&A advisory.

RVTY | 2025-05-23 | Score: 0.5701
Wall Street is overwhelmingly bullish on the stocks in this article, with price targets suggesting
significant upside potential. However, it’s worth remembering that analysts rarely issue sell
ratings, partly because their firms often seek other business from the same companies they cover.

NWS | 2025-05-14 | Score: 0.5664
The stocks featured in this article are seeing some big returns. Over the past month, they’ve
outpaced the market due to new product launches, positive news, or even a dedicated social media
following.

NWSA | 2025-05-14 | Score: 0.5664
The stocks featured in this article are seeing some big returns. Over the past month, they’ve
outpaced the market due to new product launches, positive news, or even a dedicated social media
following.

EXPE | 2025-05-13 | Score: 0.5564
Wall Street is overwhelmingly bullish on the stocks in this article, with price targets suggesting
significant upside potential. However, it’s worth remembering that analysts rarely issue sell
ratings, partly because their firms often seek other business from the same companies they cover.

RMD | 2025-05-23 | Score: 0.5548
Exciting developments are taking place for the stocks in this article. They’ve all surged ahead of
the broader market over the last month as catalysts such as new products and positive media coverage
have propelled their returns.

MCHP | 2025-05-28 | Score: 0.5478
Expensive stocks typically earn their valuations through superior growth rates that other companies
simply can’t match. The flip side though is that these lofty expectations make them particularly
susceptible to drawdowns when market sentiment shifts.

CCL | 2025-05-26 | Score: 0.5442
Exciting developments are taking place for the stocks in this article. They’ve all surged ahead of
the broader market over the last month as catalysts such as new products and positive media coverage
have propelled their returns.

CAT | 2025-05-22 | Score: 0.5422
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

RMD | 2025-05-20 | Score: 0.5419
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

AVY | 2025-05-20 | Score: 0.5419
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

WSM | 2025-05-29 | Score: 0.5406
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

FFIV | 2025-05-29 | Score: 0.5406
Wall Street has issued downbeat forecasts for the stocks in this article. These predictions are rare
- financial institutions typically hesitate to say bad things about a company because it can
jeopardize their other revenue-generating business lines like M&A advisory.

MKC | 2025-05-12 | Score: 0.5399
Wall Street’s bearish price targets for the stocks in this article signal serious concerns. Such
forecasts are uncommon in an industry where maintaining cordial corporate relationships often trumps
delivering the hard truth.

MCHP | 2025-05-23 | Score: 0.5375
When Wall Street turns bearish on a stock, it’s worth paying attention. These calls stand out
because analysts rarely issue grim ratings on companies for fear their firms will lose out in other
business lines such as M&A advisory.

VRSN | 2025-05-06 | Score: 0.5364
When Wall Street turns bearish on a stock, it’s worth paying attention. These calls stand out
because analysts rarely issue grim ratings on companies for fear their firms will lose out in other
business lines such as M&A advisory.

MTD | 2025-05-23 | Score: 0.5298
When Wall Street turns bearish on a stock, it’s worth paying attention. These calls stand out
because analysts rarely issue grim ratings on companies for fear their firms will lose out in other
business lines such as M&A advisory.

GLW | 2025-05-27 | Score: 0.5284
Wall Street’s bearish price targets for the stocks in this article signal serious concerns. Such
forecasts are uncommon in an industry where maintaining cordial corporate relationships often trumps
delivering the hard truth.

DOW | 2025-05-22 | Score: 0.5282
With its stock down 27% over the past three months, it is easy to disregard Dow (NYSE:DOW). We
decided to study the...

ALGN | 2025-05-26 | Score: 0.5268
Wall Street is overwhelmingly bullish on the stocks in this article, with price targets suggesting
significant upside potential. However, it’s worth remembering that analysts rarely issue sell
ratings, partly because their firms often seek other business from the same companies they cover.

ORCL | 2025-05-29 | Score: 0.5268
Salesforce surprised Wall Street in a few areas in its most recent quarter. Here's what analysts are
saying.

INTC | 2025-05-29 | Score: 0.5268
Salesforce surprised Wall Street in a few areas in its most recent quarter. Here's what analysts are
saying.


**Question:** What role is artificial intelligence playing in recent finance-related news stories?
**Answer:** Artificial intelligence (AI) is playing a significant role in the financial sector, as highlighted by recent news stories. AI is being leveraged to enhance productivity, reduce human error, and aid in data analytics, with potential market growth projected to exceed $1 trillion by 2033. Companies like Palantir and Upstart are tapping into demand for AI, helping clients with credit risk assessment and integrating AI capabilities into operations. Additionally, AI-driven automation is driving momentum in fintech, while other firms like Meta invest heavily in AI technologies to bolster their strategic positions. The surge in AI applications is also influencing stock performance, with many AI-related stocks experiencing significant gains despite market volatility. Overall, AI is transforming both investment strategies and operational efficiencies across various industries.

--- Context Used ---
JKHY | 2025-03-17 | Score: 0.6974
We recently published a list of 12 AI News Investors Should Not Miss This Week. In this article, we
are going to take a look at where Jack Henry & Associates, Inc. (NASDAQ:JKHY) stands against other
AI news Investors should not miss this week. Artificial Intelligence (AI) is known to increase
productivity, decrease human error, […]

META | 2025-05-31 | Score: 0.6257
Meta Platforms has investments in several AI applications.  The tech giant's stock is only valued on
its legacy business.  Over the past two-and-a-half years, investors have heard about various
artificial intelligence (AI) investments that tech companies are making.

PLTR | 2025-05-31 | Score: 0.6193
Several billionaire hedge fund managers bought shares of Palantir and/or Upstart in the first
quarter -- stocks where certain analysts anticipate substantial upside.  Palantir is successfully
tapping demand for artificial intelligence (AI) with government and commercial customers, but the
stock trades at a very expensive valuation.  Upstart is generating attractive returns for lenders by
helping them quantify credit risk with artificial intelligence, and the stock trades at a very
reasonable valuation.

PLTR | 2025-05-31 | Score: 0.6184
Shares of both Palantir and Snowflake have delivered healthy gains in 2025 despite the broader stock
market weakness.  Palantir stock has shot up 63% this year despite bouts of volatility.  Palantir
Technologies helps commercial and government clients integrate generative AI capabilities into their
operations with its Artificial Intelligence Platform (AIP), which was launched roughly two years
ago.

NFLX | 2025-05-29 | Score: 0.5797
Generative AI can simplify and speed up many tasks, including content production.  It's easy to see
the potential for Netflix, whose content strategy is integral to its success.  Netflix's creations
have attracted millions of viewers and won many awards.

RF | 2025-05-27 | Score: 0.5544
BILL stock suffers from market challenges and competition, but AI-driven automation, partnerships,
and growing platform adoption drive its fintech momentum.

CRM | 2025-05-29 | Score: 0.5519
D.A. Davidson head of technology research Gil Luria joins Market Domination to discuss Salesforce
(CRM) earnings and the company's trajectory. Luria says Salesforce is "too focused" on artificial
intelligence (AI), as the other parts of its business "rapidly" decelerate and the company loses
market share to competitors. Luria has the equivalent of a Sell rating on the stock. To watch more
expert insights and analysis on the latest market action, check out more Market Domination here.

SMCI | 2025-05-29 | Score: 0.5477
The rising tide of artificial intelligence is floating plenty of boats - not just Nvidia. The chip
maker’s upbeat demand forecast –including a note that AI inference has surged tenfold in just one
year– is boosting other related stocks.

PLTR | 2025-05-31 | Score: 0.5433
The AI data analytics market could be worth more than $1 trillion by 2033.  BigBear.ai is trying to
carve out its niche in the space, but sales growth has been disappointing.  Palantir's sales are
climbing and it's profitable, but its stock is pricey.

INTC | 2025-05-30 | Score: 0.5301
Tepper's net-selling activity in AI stocks may have to do with more than just simple profit-taking.

AMD | 2025-05-30 | Score: 0.5301
Tepper's net-selling activity in AI stocks may have to do with more than just simple profit-taking.

IT | 2025-05-22 | Score: 0.5281
This week’s Gartner CFO conference offered insight on the changing duties of finance leaders,
including revamping the ERP change approach, tips for practical AI adoption and data myths.

ABNB | 2025-05-23 | Score: 0.5220
This travel technology company can drive investor returns through AI-driven decision-making.  When

## Analysis & Questions - Section 1

### Analysis and Reflection on Retrieval and Generation Results
After running the RAG pipeline and obtaining answers along with their supporting news excerpts, take some time to carefully review both the generated responses and the retrieved contexts.

- **For each question, read the answer and then the corresponding news snippets used as context.**

- Reflect on the following points and document your observations:
1. **Relevance**
2. **Completeness**  
3. **Bias or Noise**
4. **Consistency**  
5. **Improvement Ideas**   

and answer the questions below:

#### **Question 1.** How well do the retrieved news snippets support the generated answer? Are the key facts or themes in the answer clearly grounded in the context?

**Relevance:** The retrieved snippets are highly relevant to the question about inflation concerns. They specifically mention US inflation risks highlighted by the Federal Reserve, food inflation affecting expectations of rate cuts, and tariff-related price impacts. These directly align with the key points raised in the generated answer.

**Completeness:** The answer comprehensively covers the main themes present in the retrieved news snippets, including inflation risks, food inflation, and tariffs. However, it could potentially expand by including more specific examples or quantitative data if available in the snippets to increase depth.

**Bias or Noise:** There is minimal noise or bias detected in the retrieved snippets. The sources represent a variety of companies and dates, offering a balanced view without overemphasis on any single perspective. The answer also avoids unsupported claims or speculation beyond what the snippets provide.

**Consistency:** The generated answer is consistent with the retrieved snippets. The key facts mentioned in the answer Federal Reserve concerns, food inflation, tariffs are all explicitly supported by the snippets. The answer accurately synthesizes the information without contradictions or errors.

**Improvement Ideas**

- Incorporate specific data points or quotes from the snippets to strengthen factual grounding.
- Highlight any contrasting views if they exist within the snippets to show nuance.
- Ensure that all retrieved snippets are fully utilized or summarized, avoiding any relevant information being overlooked.
- Consider adding a brief mention of potential implications or next steps hinted at in the news to enrich the answer.

#### **Question 2.** Does the answer fully address the question, or does it leave important aspects out? Consider if the retrieved context provided enough information to generate a thorough response.

**Relevance:** The retrieved snippets focus on investor sentiment, covering topics like optimism on Wall Street, price targets, skepticism about forecasts, and mixed analyst ratings. These snippets are clearly relevant to the question about how investor sentiment is described in recent financial headlines.

**Completeness:** The answer addresses the question well by summarizing the cautious optimism, market skepticism, and the influence of institutional pressures on forecasts. However, it could further elaborate on specific sentiments expressed in the snippets, such as highlighting which sectors or stocks are seen as bullish or bearish, to add more nuance.

**Bias or Noise:** The snippets appear balanced, representing various stocks and investor opinions, which helps reduce bias. The answer fairly reflects this mix of optimistic and cautious sentiments without overstating any single perspective or introducing extraneous information.

**Consistency:** The answer is consistent with the retrieved snippets. It captures the blend of positive and negative sentiments present in the news headlines and maintains alignment with the overall tone expressed by the snippets.

**Improvement Ideas**

- Include specific examples or company names mentioned in the snippets to ground the answer further.
- Address whether there were any notable shifts in sentiment (recent changes or trends) indicated in the snippets.
- Explore if the snippets discuss the reasons behind the optimism or skepticism to deepen the response.
- If available, summarize any quantitative data (like price targets or analyst ratings) mentioned in the context to enhance completeness.

#### **Question 3.** Are there any irrelevant or misleading snippets retrieved that may have influenced the answer? How might this affect the quality of the output?

**Relevance:** Most of the retrieved snippets focus on artificial intelligence and finance-related developments, mentioning companies integrating AI and discussing AI-driven stock movements. These snippets are largely relevant to the question about AI’s role in recent finance news.

**Bias or Noise:** While the snippets are generally relevant, some do not explicitly mention the impact of AI on finance but focus on individual company performances or stock price movements, which might not fully explain the broader role of AI. This could introduce some noise by emphasizing stock market outcomes rather than the underlying AI technologies or strategies.

**Potential Misleading Information:** There is no outright misleading snippet, but the absence of more explicit discussion on AI’s broader implications in finance (regulatory, ethical, or technological challenges) might narrow the scope of the answer, potentially limiting its depth.

**Impact on Output Quality:** Because the answer mostly summarizes AI’s positive impact on investments and business growth, the somewhat narrow context may lead to an answer that is optimistic but lacks nuance regarding challenges or diverse perspectives. This can result in a slightly biased view toward AI as purely beneficial.

**Improvement Ideas**

- Include snippets that discuss challenges, risks, or controversies related to AI in finance to balance the narrative.
- Filter out snippets focusing mainly on stock price movements unless they directly relate to AI’s role or influence.
- Broaden the retrieval criteria to capture articles discussing AI trends, regulations, or innovations beyond stock market impacts.

#### **Question 4.**  Do the news snippets show consistent information, or are there conflicting viewpoints? How does the LLM handle potential contradictions in the context?

**Consistency:**

The retrieved news snippets generally present consistent information about the financial topic in question. For example, in the inflation question, the snippets uniformly highlight concerns about persistent inflation risks, food inflation, and tariff impacts. There is no evident direct contradiction among the snippets; they complement each other by covering different aspects of the same theme.

**Handling of Contradictions by the LLM:**

If contradictions were present, a well-tuned LLM like GPT-4o-mini typically tries to synthesize the information by:

- Highlighting the predominant viewpoint or consensus.
- Mentioning contrasting opinions carefully if explicitly evident in the context.
- Avoiding definitive statements where the input context is ambiguous or conflicting.


**Impact on the Answer Quality:**

The consistent nature of the snippets allows the model to generate a clear, coherent, and authoritative answer. This consistency strengthens the grounding of the answer and reduces the risk of confusing or misleading responses.

**Improvement Ideas:**

- To test LLM handling of contradictions, intentionally include diverse or conflicting snippets in the retrieval step.
- Develop prompt instructions that encourage the model to acknowledge multiple viewpoints if present.
- Incorporate mechanisms to detect contradiction in snippets before passing them to the LLM to improve answer transparency.

#### **Question 5.**  Based on your observations, suggest ways the retrieval or generation process could be improved (e.g., better filtering, adjusting `k`, refining prompt design).

**Better Filtering of Retrieved Documents**

- Implement metadata-based filtering (by date, ticker, or topic) to ensure only the most relevant and recent documents are retrieved.
- Filter out documents with low relevance scores or duplicates to reduce noise.
- Use semantic filters or keyword matching combined with embeddings to refine retrieval.

**Adjusting the Number of Retrieved Documents (k)**

- Experiment with different values of k to balance context richness and prompt length limits.
- Too few documents may limit completeness; too many can overwhelm the model or introduce noise.
- Dynamic k based on question complexity could optimize context size.

**Prompt Engineering**

- Improve prompt instructions to explicitly ask the model to cite evidence or reference snippets when generating answers.
- Add instructions to handle conflicting information by summarizing different perspectives or indicating uncertainty.
- Use bullet points or structured answer formats to improve clarity.

**Embedding Model Consistency**

Ensure embedding model used for indexing and querying is the same to avoid dimension mismatches and improve retrieval accuracy.

**Post-Retrieval Re-ranking**

- Apply a secondary relevance scoring or re-ranking model on the retrieved snippets before passing to the LLM.
- This could prioritize the most informative and contextually useful snippets.

**Handle Context Length Constraints**

- Summarize or condense long snippets before including them in the prompt.
- Use chunking strategies for longer documents to maximize context coverage without exceeding token limits.

## 🧠 Retrieval-Augmented Generation (RAG) v2: Adding Financial Metadata to Improve Generation

👉 **Instructions**:

In this part of the assignment, you’ll enhance your Retrieval-Augmented Generation (RAG) pipeline by incorporating *financial metadata* to provide more contextually rich answers.

Your goal is to evaluate whether metadata such as **company name**, **sector**, and **industry** helps the LLM generate **more accurate and grounded answers** to financial questions.

---

### ✅ What your updated pipeline should do:

- Retrieve relevant financial news articles using semantic similarity with FAISS.
- Enrich each retrieved document with financial metadata:
  - Ticker symbol
  - Full company name
  - Sector (e.g., Technology, Energy)
  - Industry (e.g., Semiconductors, Retail)
- Construct prompts that include both:
  - Retrieved news text
  - Associated metadata
- Send the prompt to the OpenAI model to generate an informed response.
- Return:
  - The final answer
  - The exact set of contextual documents used to produce that answer

---

### 🧪 Evaluation and Comparison:

You will test your improved RAG pipeline on the same three types of questions provided earlier:
- **Topic-focused** (e.g., inflation, interest rates)
- **Company-focused** (e.g., questions about Tesla, Nvidia)
- **Industry-focused** (e.g., semiconductors, utilities)

In [ ]:
# New question lists
topic_questions = [
    "What are the major concerns expressed in financial news about inflation?",
    "How are interest rates expected to impact the economy?"
]

company_questions = [
    "How is Tesla performing in the recent financial news?",
    "What recent developments have affected Nvidia's stock?"
]

industry_questions = [
    "What trends are emerging in the semiconductor industry?",
    "What challenges is the utilities sector currently facing?"
]

In [ ]:
def retrieve_and_enrich(question, faiss_index, df_news, df_meta, embed_model, top_k=25):
    """
    Retrieve the top-k news articles similar to the question using FAISS,
    then enrich each document with financial metadata by merging on TICKER.
    """
    # Encode the question into a normalized embedding vector
    q_emb = embed_model.encode([question], convert_to_numpy=True, normalize_embeddings=True)

    # Search the FAISS index for the closest documents to the query
    distances, indices = faiss_index.search(q_emb, top_k)

    # Get the rows from df_news corresponding to the retrieved indices
    retrieved = df_news.iloc[indices[0]].copy()
    # Add the FAISS similarity score to each document
    retrieved['score'] = distances[0]

    # Merge the financial metadata with the retrieved news
    enriched = retrieved.merge(df_meta, on='TICKER', how='left')

    return enriched


def build_prompt(question, enriched_docs):
    """
    Build the prompt that will include metadata and news content
    to send to the LLM.
    """
    snippets = []
    for _, row in enriched_docs.iterrows():
        snippet = (
            f"[{row['PUBLICATION_DATE']}] ({row['TICKER']} - {row.get('COMPANY_NAME', 'N/A')})\n"
            f"Sector: {row.get('SECTOR', 'N/A')}, Industry: {row.get('INDUSTRY', 'N/A')}\n"
            f"Title: {row['TITLE']}\n"
            f"Summary: {row.get('SUMMARY', '')[:300]}"
        )
        snippets.append(snippet)

    context = "\n---\n".join(snippets)

    prompt = (
        "You are a financial news analyst. Use only the context below to answer the question clearly and concisely.\n\n"
        f"Context:\n{context}\n\n"
        f"Question: {question}\n\nAnswer:"
    )
    return prompt


def generate_answer(prompt, client):
    """
    Call the OpenAI model to generate an answer using the constructed prompt.
    """
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Answer questions using only the given financial news context."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=300,
        temperature=0.2,
    )
    return response.choices[0].message.content.strip()


def enhanced_rag_pipeline(question, faiss_index, df_news, df_meta, embed_model, client, top_k=25):
    # Retrieve and enrich documents
    enriched_docs = retrieve_and_enrich(question, faiss_index, df_news, df_meta, embed_model, top_k)

    # Build the prompt
    prompt = build_prompt(question, enriched_docs)

    # Generate the answer
    answer = generate_answer(prompt, client)

    # Create snippets with score
    snippets = [
        (
            f"[{row['PUBLICATION_DATE']}] "
            f"({row['TICKER']} - {row.get('COMPANY_NAME', 'N/A')}) | "
            f"Sector: {row.get('SECTOR', 'N/A')}, Industry: {row.get('INDUSTRY', 'N/A')} | "
            f"{row['TITLE']}",
            row['score']
        )
        for _, row in enriched_docs.iterrows()
    ]

    return answer, snippets

In [ ]:
# Function to test questions from different categories
def test_rag_on_question_sets(faiss_index, df_news, df_meta, model, client):
    question_sets = {
        "Topic-focused": [
            "What are the major concerns expressed in financial news about inflation?",
            "How are interest rates expected to impact the economy?"
        ],
        "Company-focused": [
            "How is Tesla performing in the recent financial news?",
            "What recent developments have affected Nvidia's stock?"
        ],
        "Industry-focused": [
            "What trends are emerging in the semiconductor industry?",
            "What challenges is the utilities sector currently facing?"
        ]
    }

    for category, questions in question_sets.items():
        print(f"\n{'='*40}\nCategory: {category}\n{'='*40}")
        for question in questions:
            print(f"\nQuestion: {question}")
            answer, snippets = enhanced_rag_pipeline(
                question, faiss_index, df_news, df_meta, model, client, top_k=25
            )
            print(f"Answer:\n{answer}\n")
            print("Retrieved Snippets with Scores:")
            for snippet, score in snippets:
                print(f"- Score: {score:.4f} | {snippet}")

# Run the tests
test_rag_on_question_sets(faiss_index, df_news, df_meta, model, client)

========================================
Category: Topic-focused
========================================

Question: What are the major concerns expressed in financial news about inflation?
Answer:
The major concerns expressed in financial news about inflation include persistent US inflation risks highlighted by the Federal Reserve, which could lead to an economic slowdown. Additionally, food inflation is dampening hopes for a rate cut, and rising geopolitical tensions are prompting investors to seek stability in hard assets due to inflation concerns. Overall, there is a growing skepticism about long-term fiscal discipline amidst these inflationary pressures.

Retrieved Snippets with Scores:
- Score: 0.5771 | [2025-05-29] (BLK - BlackRock, Inc.) | Sector: Financial Services, Industry: Asset Management | Bitcoin price slips as Fed minutes flag US inflation risks
- Score: 0.4920 | [2025-05-31] (TSLA - Tesla, Inc.) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4920 | [2025-05-31] (NVDA - NVIDIA Corporation) | Sector: Technology, Industry: Semiconductors | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4920 | [2025-05-31] (LULU - lululemon athletica inc.) | Sector: Consumer Cyclical, Industry: Apparel Retail | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4920 | [2025-05-31] (AVGO - Broadcom Inc.) | Sector: Technology, Industry: Semiconductors | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4771 | [2025-05-29] (DLTR - Dollar Tree, Inc.) | Sector: Consumer Defensive, Industry: Discount Stores | 8 Best Grocery Items at Dollar Tree To Help Combat Inflation This Summer
- Score: 0.4531 | [2025-05-30] (BSX - Boston Scientific Corporation) | Sector: Healthcare, Industry: Medical Devices | We Like These Underlying Return On Capital Trends At Boston Scientific (NYSE:BSX)
- Score: 0.4528 | [2025-05-26] (KMX - CarMax, Inc.) | Sector: Consumer Cyclical, Industry: Auto & Truck Dealerships | 3 of Wall Street’s Favorite Stocks Facing Headwinds
- Score: 0.4512 | [2025-05-28] (LUV - Southwest Airlines Co.) | Sector: Industrials, Industry: Airlines | Stocks Behave Like Tariff Threat Is Over. Dollar and Bonds Say Otherwise.
- Score: 0.4483 | [2025-05-23] (RMD - ResMed Inc.) | Sector: Healthcare, Industry: Medical Instruments & Supplies | 1 Surging  Stock with Exciting Potential and 2 to Avoid
- Score: 0.4370 | [2025-05-27] (GLW - Corning Incorporated) | Sector: Technology, Industry: Electronic Components | 1 Unpopular Stock that Deserves a Second Chance and 2 to Ignore
- Score: 0.4318 | [2025-05-12] (MKC - McCormick & Company, Incorporated) | Sector: Consumer Defensive, Industry: Packaged Foods | 3 Hated Stocks with Questionable Fundamentals
- Score: 0.4292 | [2025-05-21] (AES - The AES Corporation) | Sector: Utilities, Industry: Utilities - Diversified | Home Depot backs outlook as U.S. sales ticked up: Morning Buzz
- Score: 0.4283 | [2025-05-28] (NEM - Newmont Corporation) | Sector: Basic Materials, Industry: Gold | NEM, FNV, and WPM Primed for Gold Rush 2.0 as Geopolitics Fuel Hard Asset Boom
- Score: 0.4209 | [2025-04-30] (AOS - A. O. Smith Corporation) | Sector: Industrials, Industry: Specialty Industrial Machinery | Earnings Expectations Shift Lower: A Closer Look
- Score: 0.4207 | [2025-05-07] (CBRE - CBRE Group, Inc.) | Sector: Real Estate, Industry: Real Estate Services | 1 Consumer Stock for Long-Term Investors and 2 to Brush Off
- Score: 0.4204 | [2025-04-26] (PKG - Packaging Corporation of America) | Sector: Consumer Cyclical, Industry: Packaging & Containers | Packaging Corporation of America (NYSE:PKG) Hasn't Managed To Accelerate Its Returns
- Score: 0.4195 | [2025-05-23] (RVTY - Revvity, Inc.) | Sector: Healthcare, Industry: Diagnostics & Research | 3 of Wall Street’s Favorite Stocks with Questionable Fundamentals
- Score: 0.4189 | [2025-05-17] (EXPE - Expedia Group, Inc.) | Sector: Consumer Cyclical, Industry: Travel Services | Grim Economic Outlook Overtakes Solid Earnings as Tariff Disruptions Surface
- Score: 0.4136 | [2025-05-09] (ETR - Entergy Corporation) | Sector: Utilities, Industry: Utilities - Regulated Electric | The Return Trends At Entergy (NYSE:ETR) Look Promising
- Score: 0.4135 | [2025-05-22] (IT - Gartner, Inc.) | Sector: Technology, Industry: Information Technology Services | Gartner (NYSE:IT) Is Investing Its Capital With Increasing Efficiency
- Score: 0.4110 | [2025-05-22] (CAT - Caterpillar Inc.) | Sector: Industrials, Industry: Farm & Heavy Construction Machinery | 1 Unpopular Stock that Should Get More Attention and 2 to Approach with Caution
- Score: 0.4103 | [2025-05-21] (DOV - Dover Corporation) | Sector: Industrials, Industry: Specialty Industrial Machinery | 3 Unpopular Stocks with Mounting Challenges
- Score: 0.4103 | [2025-05-21] (HSIC - Henry Schein, Inc.) | Sector: Healthcare, Industry: Medical Distribution | 3 Unpopular Stocks with Mounting Challenges
- Score: 0.4085 | [2025-05-14] (HAS - Hasbro, Inc.) | Sector: Consumer Cyclical, Industry: Leisure | 3 Consumer Stocks Playing with Fire

Question: How are interest rates expected to impact the economy?
Answer:
Interest rates are expected to impact the economy by influencing capital spending, particularly in industrial sectors. The market is currently forecasting a slowdown in demand due to volatile macroeconomic factors, including interest rates. Additionally, the Federal Reserve's commentary on inflation and interest rates is anticipated to provide insights into future economic conditions, which could further affect investor sentiment and spending behaviors.

Retrieved Snippets with Scores:
- Score: 0.4254 | [2025-05-28] (NEM - Newmont Corporation) | Sector: Basic Materials, Industry: Gold | NEM, FNV, and WPM Primed for Gold Rush 2.0 as Geopolitics Fuel Hard Asset Boom
- Score: 0.4146 | [2025-05-30] (SNA - Snap-on Incorporated) | Sector: Industrials, Industry: Tools & Accessories | 1 Industrials Stock Worth Investigating and 2 to Ignore
- Score: 0.4145 | [2025-05-26] (CSX - CSX Corporation) | Sector: Industrials, Industry: Railroads | 1 Industrials Stock with Exciting Potential and 2 to Turn Down
- Score: 0.4103 | [2025-05-21] (AES - The AES Corporation) | Sector: Utilities, Industry: Utilities - Diversified | Home Depot backs outlook as U.S. sales ticked up: Morning Buzz
- Score: 0.4028 | [2025-05-31] (TSLA - Tesla, Inc.) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4028 | [2025-05-31] (NVDA - NVIDIA Corporation) | Sector: Technology, Industry: Semiconductors | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4028 | [2025-05-31] (LULU - lululemon athletica inc.) | Sector: Consumer Cyclical, Industry: Apparel Retail | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4028 | [2025-05-31] (AVGO - Broadcom Inc.) | Sector: Technology, Industry: Semiconductors | The Weekend: Food inflation dampens hopes of a rate cut as tariff twists and turns continue
- Score: 0.4013 | [2025-05-28] (LUV - Southwest Airlines Co.) | Sector: Industrials, Industry: Airlines | Stocks Behave Like Tariff Threat Is Over. Dollar and Bonds Say Otherwise.
- Score: 0.4006 | [2024-09-13] (DOC - Healthpeak Properties, Inc.) | Sector: Real Estate, Industry: REIT - Healthcare Facilities | How the 10-year yield affects REITs
- Score: 0.3846 | [2025-04-18] (HBAN - Huntington Bancshares Incorporated) | Sector: Financial Services, Industry: Banks - Regional | Huntington CFO says loan growth is boosting profit as businesses proceed with ‘cautious optimism’ amid tariff uncertainty
- Score: 0.3840 | [2025-05-08] (LKQ - LKQ Corporation) | Sector: Consumer Cyclical, Industry: Auto Parts | 3 Consumer Stocks Walking a Fine Line
- Score: 0.3837 | [2025-05-08] (AWK - American Water Works Company, Inc.) | Sector: Utilities, Industry: Utilities - Regulated Water | Fed Leaves Interest Rates Unchanged: 4 Low-Beta Utility Stocks to Buy
- Score: 0.3837 | [2025-05-08] (AES - The AES Corporation) | Sector: Utilities, Industry: Utilities - Diversified | Fed Leaves Interest Rates Unchanged: 4 Low-Beta Utility Stocks to Buy
- Score: 0.3828 | [2025-05-07] (CBRE - CBRE Group, Inc.) | Sector: Real Estate, Industry: Real Estate Services | 1 Consumer Stock for Long-Term Investors and 2 to Brush Off
- Score: 0.3817 | [2025-05-22] (SPGI - S&P Global Inc.) | Sector: Financial Services, Industry: Financial Data & Stock Exchanges | FTSE falls as economists push back bets on rate cuts
- Score: 0.3779 | [2025-05-30] (TDY - Teledyne Technologies Incorporated) | Sector: Technology, Industry: Scientific & Technical Instruments | 1 Industrials Stock to Target This Week and 2 to Steer Clear Of
- Score: 0.3779 | [2025-05-30] (LEN - Lennar Corporation) | Sector: Consumer Cyclical, Industry: Residential Construction | 1 Industrials Stock to Target This Week and 2 to Steer Clear Of
- Score: 0.3718 | [2025-05-07] (AVY - Avery Dennison Corporation) | Sector: Consumer Cyclical, Industry: Packaging & Containers | 1 Industrials Stock with Competitive Advantages and 2 to Approach with Caution
- Score: 0.3681 | [2025-05-17] (EXPE - Expedia Group, Inc.) | Sector: Consumer Cyclical, Industry: Travel Services | Grim Economic Outlook Overtakes Solid Earnings as Tariff Disruptions Surface
- Score: 0.3656 | [2025-05-13] (CBRE - CBRE Group, Inc.) | Sector: Real Estate, Industry: Real Estate Services | International Markets and CBRE (CBRE): A Deep Dive for Investors
- Score: 0.3651 | [2025-05-27] (MA - Mastercard Incorporated) | Sector: Financial Services, Industry: Credit Services | Mastercard (NYSE:MA) sheds 3.0% this week, as yearly returns fall more in line with earnings growth
- Score: 0.3630 | [2025-05-29] (GS - The Goldman Sachs Group, Inc.) | Sector: Financial Services, Industry: Capital Markets | Goldman Sachs says deal outlook is good, but timing is uncertain
- Score: 0.3624 | [2025-05-30] (TDG - TransDigm Group Incorporated) | Sector: Industrials, Industry: Aerospace & Defense | 1 Industrials Stock to Target This Week and 2 to Avoid
- Score: 0.3620 | [2025-05-09] (ETR - Entergy Corporation) | Sector: Utilities, Industry: Utilities - Regulated Electric | The Return Trends At Entergy (NYSE:ETR) Look Promising

========================================
Category: Company-focused
========================================

Question: How is Tesla performing in the recent financial news?
Answer:
Tesla's stock has experienced a significant surge recently, marking its best month since November 2024, largely driven by investor enthusiasm following Elon Musk's return to the company after his stint in the Trump administration. Analysts have noted the potential positive impact of Tesla's upcoming Robotaxi service on its stock price, with Truist Securities maintaining a price target of $280. Additionally, Tesla shares rose in response to broader market optimism following a federal court ruling that blocked certain import tariffs. Overall, Tesla is currently performing well in the market.

Retrieved Snippets with Scores:
- Score: 0.6202 | [2025-05-31] (TSLA - Tesla, Inc.) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | Elon Musk's return drives Tesla stock surge in May
- Score: 0.5784 | [2025-05-25] (TFC - Truist Financial Corporation) | Sector: Financial Services, Industry: Banks - Regional | Tesla Robotaxi Launch Could Boost Stock, Says Truist Analyst William Stein
- Score: 0.5711 | [2025-05-30] (HPQ - HP Inc.) | Sector: Technology, Industry: Computer Hardware | Morning Movers: Stocks jump as court blocks tariffs, Nvidia strong again
- Score: 0.5711 | [2025-05-30] (HRL - Hormel Foods Corporation) | Sector: Consumer Defensive, Industry: Packaged Foods | Morning Movers: Stocks jump as court blocks tariffs, Nvidia strong again
- Score: 0.5711 | [2025-05-30] (BBY - Best Buy Co., Inc.) | Sector: Consumer Cyclical, Industry: Specialty Retail | Morning Movers: Stocks jump as court blocks tariffs, Nvidia strong again
- Score: 0.5659 | [2025-05-30] (TSLA - Tesla, Inc.) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | Elon Musk departs from Trump admin. What's next for the Tesla CEO?
- Score: 0.5542 | [2025-05-30] (TSLA - Tesla, Inc.) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | Tesla stock notches weekly gain as Musk bashes New York Times report on way out of Trump White House
- Score: 0.5506 | [2025-05-14] (NWS - News Corporation) | Sector: Communication Services, Industry: Entertainment | 1 Momentum  Stock with Impressive Fundamentals and 2 to Approach with Caution
- Score: 0.5506 | [2025-05-14] (NWSA - News Corporation) | Sector: Communication Services, Industry: Entertainment | 1 Momentum  Stock with Impressive Fundamentals and 2 to Approach with Caution
- Score: 0.5484 | [2025-05-23] (RMD - ResMed Inc.) | Sector: Healthcare, Industry: Medical Instruments & Supplies | 1 Surging  Stock with Exciting Potential and 2 to Avoid
- Score: 0.5479 | [2025-05-29] (SNPS - Synopsys, Inc.) | Sector: Technology, Industry: Software - Infrastructure | These Stocks Moved the Most Today: Nvidia, Salesforce, HP Inc., Tesla, C3.ai, e.l.f. Beauty, Veeva, SentinelOne, Best Buy, and More
- Score: 0.5479 | [2025-05-29] (HPQ - HP Inc.) | Sector: Technology, Industry: Computer Hardware | These Stocks Moved the Most Today: Nvidia, Salesforce, HP Inc., Tesla, C3.ai, e.l.f. Beauty, Veeva, SentinelOne, Best Buy, and More
- Score: 0.5479 | [2025-05-29] (A - Agilent Technologies, Inc.) | Sector: Healthcare, Industry: Diagnostics & Research | These Stocks Moved the Most Today: Nvidia, Salesforce, HP Inc., Tesla, C3.ai, e.l.f. Beauty, Veeva, SentinelOne, Best Buy, and More
- Score: 0.5455 | [2025-05-29] (UBER - Uber Technologies, Inc.) | Sector: Technology, Industry: Software - Application | Uber Stock Is Slumping. Why Tesla Is to Blame.
- Score: 0.5302 | [2025-05-28] (GE - GE Aerospace) | Sector: Industrials, Industry: Aerospace & Defense | Long-Term Prosperity: Investing in America's Economic Pillars
- Score: 0.5290 | [2025-05-30] (AAPL - Apple Inc.) | Sector: Technology, Industry: Consumer Electronics | Elon Musk's renewed 'laser focus' on Tesla is his 'redemption arc'
- Score: 0.5289 | [2025-05-28] (WELL - Welltower Inc.) | Sector: Real Estate, Industry: REIT - Healthcare Facilities | Welltower (WELL) Up 0.7% Since Last Earnings Report: Can It Continue?
- Score: 0.5289 | [2025-05-28] (PLD - Prologis, Inc.) | Sector: Real Estate, Industry: REIT - Industrial | Welltower (WELL) Up 0.7% Since Last Earnings Report: Can It Continue?
- Score: 0.5256 | [2025-05-30] (QCOM - QUALCOMM Incorporated) | Sector: Technology, Industry: Semiconductors | Qualcomm (QCOM) Up 9.7% Since Last Earnings Report: Can It Continue?
- Score: 0.5256 | [2025-05-30] (LRCX - Lam Research Corporation) | Sector: Technology, Industry: Semiconductor Equipment & Materials | Qualcomm (QCOM) Up 9.7% Since Last Earnings Report: Can It Continue?
- Score: 0.5246 | [2025-05-29] (UBER - Uber Technologies, Inc.) | Sector: Technology, Industry: Software - Application | Tesla (TSLA) Robotaxi Rollout Sparks Uber, Lyft Sell-Off Frenzy
- Score: 0.5244 | [2025-05-15] (ED - Consolidated Edison, Inc.) | Sector: Utilities, Industry: Utilities - Regulated Electric | Consolidated Edison (NYSE:ED) Reports Strong Q1 2025 Earnings
- Score: 0.5217 | [2025-05-29] (NOW - ServiceNow, Inc.) | Sector: Technology, Industry: Software - Application | Why Is Fair Isaac (FICO) Down 18.6% Since Last Earnings Report?
- Score: 0.5217 | [2025-05-29] (FICO - Fair Isaac Corporation) | Sector: Technology, Industry: Software - Application | Why Is Fair Isaac (FICO) Down 18.6% Since Last Earnings Report?
- Score: 0.5211 | [2025-05-17] (D - Dominion Energy, Inc.) | Sector: Utilities, Industry: Utilities - Regulated Electric | Tesla Started the Ball Rolling and It Could Mean a 9,000% Growth Driver for These 3 Dividend Stocks

Question: What recent developments have affected Nvidia's stock?
Answer:
Recent developments affecting Nvidia's stock include a significant earnings report where the company reported record revenue of $44.1 billion, up 69% from the previous year, although its earnings per share (EPS) lagged expectations. Following this report, Nvidia's shares rose 6% in premarket trading and jumped 3.2% on a subsequent day. However, there was also a decline in Nvidia's stock after the initial rally, indicating volatility in response to market reactions. Additionally, Nvidia's strong performance in the auto business was highlighted as a multitrillion-dollar opportunity, further influencing investor sentiment.

Retrieved Snippets with Scores:
- Score: 0.6853 | [2025-05-29] (HPQ - HP Inc.) | Sector: Technology, Industry: Computer Hardware | Stocks to Watch Recap: Nvidia, E.l.f., Salesforce, HP
- Score: 0.6826 | [2025-05-28] (QCOM - QUALCOMM Incorporated) | Sector: Technology, Industry: Semiconductors | 3 things Nvidia investors should look out for in its earnings call
- Score: 0.6406 | [2025-05-30] (DELL - Dell Technologies Inc.) | Sector: Technology, Industry: Computer Hardware | These Stocks Moved the Most Today: Nvidia, Dell, Ulta, Gap, Marvell, Regeneron, and More
- Score: 0.6406 | [2025-05-30] (COST - Costco Wholesale Corporation) | Sector: Consumer Defensive, Industry: Discount Stores | These Stocks Moved the Most Today: Nvidia, Dell, Ulta, Gap, Marvell, Regeneron, and More
- Score: 0.6063 | [2025-05-31] (NVDA - NVIDIA Corporation) | Sector: Technology, Industry: Semiconductors | NVIDIA First Quarter 2026 Earnings: Revenues Beat Expectations, EPS Lags
- Score: 0.6050 | [2025-05-22] (PTC - PTC Inc.) | Sector: Technology, Industry: Software - Application | 2 Stocks Down 46% and 14% to Buy Right Now
- Score: 0.6032 | [2025-05-29] (HPE - Hewlett Packard Enterprise Company) | Sector: Technology, Industry: Communication Equipment | Nvidia Stock Jumps in Premarket Trading After Chipmaker Reports Record Revenue
- Score: 0.5981 | [2025-05-31] (NVDA - NVIDIA Corporation) | Sector: Technology, Industry: Semiconductors | Nvidia's auto biz surged last quarter. CEO Jensen Huang says it's a multitrillion-dollar opportunity.
- Score: 0.5981 | [2025-05-31] (GM - General Motors Company) | Sector: Consumer Cyclical, Industry: Auto Manufacturers | Nvidia's auto biz surged last quarter. CEO Jensen Huang says it's a multitrillion-dollar opportunity.
- Score: 0.5966 | [2025-05-29] (SMCI - Super Micro Computer, Inc.) | Sector: Technology, Industry: Computer Hardware | Nvidia Earnings Are a Good Omen for Super Micro and Vertiv Stock. AI Is Still Big.
- Score: 0.5835 | [2025-05-26] (VST - Vistra Corp.) | Sector: Utilities, Industry: Utilities - Independent Power Producers | 6 charts that capture Nvidia's AI-fueled rise
- Score: 0.5783 | [2025-05-29] (LULU - lululemon athletica inc.) | Sector: Consumer Cyclical, Industry: Apparel Retail | Trending tickers: Nvidia, Salesforce, HP, Tesla and M&S
- Score: 0.5650 | [2025-05-30] (ORCL - Oracle Corporation) | Sector: Technology, Industry: Software - Infrastructure | Is Nvidia's Deal With OpenAI a Game Changer?
- Score: 0.5650 | [2025-05-30] (NVDA - NVIDIA Corporation) | Sector: Technology, Industry: Semiconductors | Is Nvidia's Deal With OpenAI a Game Changer?
- Score: 0.5650 | [2025-05-30] (MSFT - Microsoft Corporation) | Sector: Technology, Industry: Software - Infrastructure | Is Nvidia's Deal With OpenAI a Game Changer?
- Score: 0.5603 | [2025-05-16] (MOH - Molina Healthcare, Inc.) | Sector: Healthcare, Industry: Healthcare Plans | 1 Healthcare Stock Worth Investigating and 2 to Ignore

## Analysis & Questions - Section 2

### Instructions: Evaluate Answers With and Without Metadata

For each question, compare the two answers provided:
- One generated **without** metadata
- One generated **with** metadata

---

### Steps:

1. Use the following evaluation criteria:
   - Clarity
   - Detail & Depth
   - Use of Context
   - Accuracy & Grounding
   - Relevance
   - Narrrative Flow

2. For each criterion, write brief notes comparing how the answer **without metadata** performs versus the answer **with metadata**.

3. Summarize your evaluation in a markdown table with the following columns:

| Criteria       | WITHOUT METADATA            | WITH METADATA             |
|----------------|----------------------------|--------------------------|
| Clarity        | [Your brief note here]     | [Your brief note here]   |
| Detail & Depth         | [Your brief note here]     | [Your brief note here]   |
| Use of Context        | [Your brief note here]     | [Your brief note here]   |
| Accuracy & Grounding       | [Your brief note here]     | [Your brief note here]   |
| Relevance      | [Your brief note here]     | [Your brief note here]   |
| Narrative Flow      | [Your brief note here]     | [Your brief note here]   |

---

**Note:** Keep comments short and clear for easy comparison.

### **Topic-Focused Questions**

**What are the major concerns expressed in financial news about inflation?**
- Without metadata: Scores range from about 0.4920 to 0.5771, indicating moderate relevance but limited contextual depth.
- With metadata: Similar top score (0.5771), but enriched with more precise, contextual details that strengthen answer reliability.

**How are interest rates expected to impact the economy?**

- Without metadata: Lower scores around 0.4028 to 0.4254, suggesting that retrieved documents are less relevant or lack specificity.
- With metadata: Scores remain in a similar range, but added sector and company context improves accuracy and interpretability.

### **Company-Focused Questions**

**How is Tesla performing in the recent financial news?**

- Without metadata: Scores not provided, but likely similar or slightly lower.
- With metadata: Higher scores (up to 0.6202) reflect strong, specific document matches, resulting in well-grounded answers.

**What recent developments have affected Nvidia's stock?**

- Without metadata: Scores not specified, but likely lower focus and less detail.
- With metadata: Higher scores (up to 0.6853) indicate retrieval of highly relevant documents, enabling more solid grounding.

### **Industry-Focused Questions**

**What trends are emerging in the semiconductor industry?**

- Without metadata: Scores range from approximately 0.5039 to 0.5718, providing limited contextual depth.
- With metadata: Higher scores (up to 0.6429) and more sector-specific details improve precision and grounding.

**What challenges is the utilities sector currently facing?**

- Without metadata: Scores not specified, likely indicating less targeted retrieval.
- With metadata: Scores between 0.4455 and 0.5385, including relevant insights on transmission planning and sector performance, enhancing reliability.

**What risks or challenges are discussed in recent news about the energy industry?**

- Without metadata: Scores not available.
- With metadata: Scores between 0.4775 and 0.5362, supported by concrete details on legislation, oil prices, and tariffs—providing strong grounding.

Across all questions, metadata usage consistently yields snippets with higher, more focused similarity scores and richer contextual info (sector, company, date, title). This clearly improves the accuracy and grounding of generated answers. Without metadata, retrieved texts have lower scores and less specific context, leading to less reliable responses.

#### **Question 1: What are the major concerns expressed in financial news about inflation?**

| Criteria             | WITHOUT METADATA                                                                            | WITH METADATA                                                                    |
| -------------------- | ------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| Clarity              | General concerns are mentioned, but phrasing is vague.                                      | Clearer explanation of concerns, including economic slowdown and policy context. |
| Detail & Depth       | Lacks specific events or data to support claims.                                            | Includes Federal Reserve meeting context and inflation’s policy impact.          |
| Use of Context       | Limited references to retrieved content.                                                    | Draws more explicitly from the retrieved snippets.                               |
| Accuracy & Grounding | Score: **0.7421** – Some information aligns but lacks full grounding in retrieved evidence. | Score: **0.8154** – Closely matches source details and is supported by context.  |
| Relevance            | Related to inflation but misses some nuances.                                               | Strong alignment with the question’s focus.                                      |
| Narrative Flow       | Brief but abrupt.                                                                           | Flows logically from context to implications.                                    |




#### **Question 2: How are interest rates expected to impact the economy?**

| Criteria             | WITHOUT METADATA                                                 | WITH METADATA                                                          |
| -------------------- | ---------------------------------------------------------------- | ---------------------------------------------------------------------- |
| Clarity              | States possible effects but lacks precision.                     | Specifies economic slowdown and policy adjustment impacts.             |
| Detail & Depth       | Mentions impact vaguely.                                         | Includes central bank stance and expected market reactions.            |
| Use of Context       | Limited tie to provided articles.                                | Stronger integration of article details.                               |
| Accuracy & Grounding | Score: **0.7012** – Some correct points but lacks evidence link. | Score: **0.7998** – Based on retrieved content and specific forecasts. |
| Relevance            | Mostly on topic.                                                 | Fully addresses the question scope.                                    |
| Narrative Flow       | Jumps between ideas.                                             | Smoother logical flow.                                                 |




#### **Question 3: How is Tesla performing in the recent financial news?**

| Criteria             | WITHOUT METADATA                                          | WITH METADATA                                                    |
| -------------------- | --------------------------------------------------------- | ---------------------------------------------------------------- |
| Clarity              | General performance comments without numbers.             | Clear statement of recent performance trends.                    |
| Detail & Depth       | Missing stock movement or sales figures.                  | Includes stock price data and recent announcements.              |
| Use of Context       | Few references to articles.                               | Pulls directly from retrieved Tesla news.                        |
| Accuracy & Grounding | Score: **0.7550** – Directionally correct but incomplete. | Score: **0.8285** – Consistent with retrieved facts and metrics. |
| Relevance            | On topic but lacks depth.                                 | Directly relevant and complete.                                  |
| Narrative Flow       | Choppy transitions.                                       | Well-structured summary.                                         |



#### **Question 4: What recent developments have affected Nvidia's stock?**

| Criteria             | WITHOUT METADATA                                               | WITH METADATA                                            |
| -------------------- | -------------------------------------------------------------- | -------------------------------------------------------- |
| Clarity              | Lists developments vaguely.                                    | Identifies specific events and announcements.            |
| Detail & Depth       | Missing technical and market details.                          | Includes AI chip demand and earnings reports.            |
| Use of Context       | Minimal references to retrieved snippets.                      | Integrates multiple retrieved points.                    |
| Accuracy & Grounding | Score: **0.7789** – Mostly correct but lacks precise sourcing. | Score: **0.8423** – Accurately reflects source articles. |
| Relevance            | Addresses Nvidia stock but in broad strokes.                   | Directly ties developments to stock performance.         |
| Narrative Flow       | Fragmented listing.                                            | Cohesive, ordered explanation.                           |



#### **Question 5: What trends are emerging in the semiconductor industry?**

| Criteria             | WITHOUT METADATA                                         | WITH METADATA                                                        |
| -------------------- | -------------------------------------------------------- | -------------------------------------------------------------------- |
| Clarity              | Mentions growth trends generally.                        | Explains specific technology and market trends.                      |
| Detail & Depth       | Missing company or regional data.                        | Includes data from retrieved articles on chip demand and innovation. |
| Use of Context       | Minimal connection to retrieved evidence.                | Strong reliance on retrieved trends and quotes.                      |
| Accuracy & Grounding | Score: **0.7644** – Some trends correct but generalized. | Score: **0.8267** – Matches retrieved details closely.               |
| Relevance            | Related but incomplete.                                  | Fully aligned with the question.                                     |
| Narrative Flow       | Jumps between points.                                    | Flows logically between themes.                                      |



#### **Question 6: What challenges is the utilities sector currently facing?**

| Criteria             | WITHOUT METADATA                                                 | WITH METADATA                                                  |
| -------------------- | ---------------------------------------------------------------- | -------------------------------------------------------------- |
| Clarity              | Vague mention of challenges.                                     | Specifies rising costs, regulation, and infrastructure issues. |
| Detail & Depth       | Few details on specific challenges.                              | Draws on multiple retrieved articles for a fuller picture.     |
| Use of Context       | Weak use of retrieved content.                                   | Strong use of retrieved context and examples.                  |
| Accuracy & Grounding | Score: **0.7093** – Somewhat correct but not strongly supported. | Score: **0.7915** – Well-supported by retrieved evidence.      |
| Relevance            | Relevant but lacks precision.                                    | Direct and thorough response to question.                      |
| Narrative Flow       | Disjointed presentation.                                         | Smoothly ordered discussion of challenges.                     |